---
title: 'Qualitative Approach'
subtitle: Read Section 1.3, 1.5-7
sidebar: notes
--- 

## Existence and Uniqueness

Before we try to analyze a inital value problem like: $$\frac{dy}{dt}=f(t,y), \quad y(t_0)=y_0$$
using a qualitative or numerical approach, it is important to know the answer to two questions: 

 - Does a solution exist? 
 - Are solutions unique? 

Answering *yes* to the first question means that there is a function $y(t)$ defined on some open interval $I\subset \mathbb R$ containing $t_0$ that satisfies both the initial condition and the differential equation for all $t$ in the interval $I$.

The following example illustrates what can go wrong.

### Problem 1: Existence

(a) Explain why the initial value problem (note how it is written a different way!): $$y\cdot\frac{dy}{dt}-1 = 0, \quad y(t_0)=y_0$$
has no solution when $y_0=0$.
(b) Explain why the initial value problem:
$$\frac{dy}{dt}=\text{sign}(t), \quad y(t_0)=y_0$$
has no solution when $t_0=0$.   

**Warning:** If a solution exists, it does not necessarily mean it will be defined for all time!

### Problem 2: Interval of Existence
Solve the initial value problem $$\frac{dy}{dt} = 1+y^2, \quad y(0)=0$$. Determine the *interval of existence* for $y(t)$, i.e. the largest possible open interval $I$ containing $t=0$ on which the solution $y(t)$ is defined.

The second question we have to address is whether or not a solution to an initial value problem is unique. 

This is particularly important for mathematical modeling. If we are using a differential equation to try and predict how some real world system will evolve, we want to know that that our model predicts a unique outcome!

The following example illustrates how uniqueness can fail.

### Problem 3: Uniqueness
Find at least two functions $y(t)$ satisfying the initial value problem: $$\frac{dy}{dt}=y^{2/3}, \quad y(1)=0$$.

## Revisiting Slope Fields

### Problem 4: Temperature Change
Suppose you lost power inside your home and the temperature inside the building is changing as heat is exchanged through the exterior of the building. 

Let $B$ be the temperature inside your home and $E$ be the temperature outside your home. Assume that:

- The external temperature $E$ is constant.
- The rate of change of the temperature inside your home is proportional to the difference between the external and internal temperatures.

Based on these assumptions:

a. Write a differential equation modeling the rate of change of the temperature inside of your home.
b. Sketch the slope field for this differential equation.
c. Explain the different scenarios for how $B(t)$ is expected to change as $t\to\infty$.
d. Explain how you are implicitly using the Existence and Uniqueness theorems in your conclusions for part (c).
e. Now suppose $E$ is not constant but fluctuates sinusoidally over time, e.g. $$E(t)=A\sin(k(t-T))+E_T$$
what effect does this have on the long-term behavior of $B(t)$? Again, use a slope field to help you make your guess. [Here is a link to a Desmos graph](https://www.desmos.com/calculator/sfbgjlcmlw) you can modify to help you make your conclusions.

