---
title: 'Slope Fields, Phase Lines, and Bifurcations'
subtitle: 'Read Sections 1.3, 1.6-7'
sidebar: notes
---

## Revisiting Slope Fields

### Problem 1: Temperature Change
Suppose you lost power inside your home and the temperature inside the building is changing as heat is exchanged through the exterior of the building. 

Let $H$ be the temperature inside your home and $E$ be the temperature outside your home. Assume that:

- The external temperature $E$ is constant.
- The rate of change of the temperature inside your home is proportional to the difference between the external and internal temperatures.

Based on these assumptions:

a. Write a differential equation modeling the rate of change of the temperature inside of your home.
b. Sketch the slope field for this differential equation.
c. Explain the different scenarios for how $H(t)$ is expected to change as $t\to\infty$.
d. Explain how you are implicitly using the Existence and Uniqueness theorems in your conclusions for part (c).
e. Now suppose $E$ is not constant but fluctuates sinusoidally over time, e.g. $$E(t)=A\sin(k(t-T))+E_T$$
what effect does this have on the long-term behavior of $H(t)$? Again, use a slope field to help you make your guess. [Here is a link to a Desmos graph](https://www.desmos.com/calculator/sfbgjlcmlw) you can modify to help you make your conclusions.

## Autonomous Systems - Phase Lines

### Problem 2: Population Growth

In the absence of external factors, a simple model for how a population size $P$ evolves over time is to assume that it changes at a rate proportional to its size. Another way of saying this is to assume that the *relative growth rate* of the population is constant.

a. Write the differential equation modeling the rate of change of the population assuming its *relative growth rate* is constant. How will $P$ change over time under this assumption?

b. Ignoring external factors is not very realistic in the long-run. As the population grows, resources will be scarcer (food, shelter, etc.) and this will impact the growth rate. So, to make our model more realistic, we can assume that the relative growth rate starts initially (when $P$ is close to 0) at some *intrinsic growth rate* $r$, but then decreases linearly *with respect to the population size*. 

    The relative growth rate will become 0 as the population size approaches some threshold $N$ determined by the limits of the surrounding environment to support the population. This parameter is often called the *carrying capacity* for the environment.

    i. Write a differential equation modeling the rate of change of the population under these assumptions.
    ii. Find all equilibrium solutions for the equation. Use a phase line to analyze their stability.
    iii. In general, how do we expect the population size $P$ to change under these assumptions?

c. Other external factors can also impact the growth rate of a population. For example, consider our previous model, and now assume that the population is something that is harvested for food by humans (e.g. blue crabs in the Chesapeake Bay). Lets assume that the species is harvested at a rate of $H$ individuals per unit time (where $H$ is a constant that is set by a regulatory agency).

    i. Adapt your model from part (b) to include the harvesting rate $H$.
    ii. How will the equilibria and their stability depend on $H$?